import Foundation

enum CaptureSkipReason: String, Codable, Equatable {
    case concealed
    case transient
    case autoGenerated
}

enum CapturePolicyDecision: Equatable {
    case capture
    case skip(CaptureSkipReason)
}

struct PasteboardCapturePolicy {
    private let configuration: Configuration

    private static let concealedMarkers = [
        "org.nspasteboard.concealedtype",
        "com.agilebits.onepassword",
        "com.1password",
        "com.lastpass",
        "org.keepassxc"
    ]
    private static let transientMarker = "org.nspasteboard.transienttype"
    private static let autoGeneratedMarker = "org.nspasteboard.autogeneratedtype"

    init(configuration: Configuration) {
        self.configuration = configuration
    }

    func decision(for typeIdentifiers: [String]) -> CapturePolicyDecision {
        let normalized = typeIdentifiers.map { $0.lowercased() }

        if !configuration.captureConcealed && normalized.contains(where: isConcealed) {
            return .skip(.concealed)
        }
        if !configuration.captureTransient && normalized.contains(Self.transientMarker) {
            return .skip(.transient)
        }
        if !configuration.captureAutoGenerated && normalized.contains(Self.autoGeneratedMarker) {
            return .skip(.autoGenerated)
        }
        return .capture
    }

    private func isConcealed(_ typeIdentifier: String) -> Bool {
        Self.concealedMarkers.contains { marker in
            typeIdentifier == marker || typeIdentifier.hasPrefix(marker + ".")
        }
    }
}
