import Foundation

public struct Configuration: Codable, Equatable, Sendable {
    public var maximumHistoryCount: Int
    public var maximumDiskBytes: UInt64
    public var maximumSingleSnapshotBytes: UInt64
    public var pollIntervalMilliseconds: Int
    public var captureConcealed: Bool
    public var captureTransient: Bool
    public var captureAutoGenerated: Bool
    public var startEnabled: Bool
    public var showContentPreviews: Bool

    public init(
        maximumHistoryCount: Int,
        maximumDiskBytes: UInt64,
        maximumSingleSnapshotBytes: UInt64,
        pollIntervalMilliseconds: Int,
        captureConcealed: Bool,
        captureTransient: Bool,
        captureAutoGenerated: Bool,
        startEnabled: Bool,
        showContentPreviews: Bool
    ) {
        self.maximumHistoryCount = maximumHistoryCount
        self.maximumDiskBytes = maximumDiskBytes
        self.maximumSingleSnapshotBytes = maximumSingleSnapshotBytes
        self.pollIntervalMilliseconds = pollIntervalMilliseconds
        self.captureConcealed = captureConcealed
        self.captureTransient = captureTransient
        self.captureAutoGenerated = captureAutoGenerated
        self.startEnabled = startEnabled
        self.showContentPreviews = showContentPreviews
    }

    public static let `default` = Configuration(
        maximumHistoryCount: 100,
        maximumDiskBytes: 104_857_600,
        maximumSingleSnapshotBytes: 2_147_483_648,
        pollIntervalMilliseconds: 400,
        captureConcealed: false,
        captureTransient: false,
        captureAutoGenerated: false,
        startEnabled: true,
        showContentPreviews: true
    )

    var effectiveMaximumSnapshotBytes: UInt64 {
        min(maximumSingleSnapshotBytes, maximumDiskBytes)
    }

    func validate() throws {
        guard maximumHistoryCount > 0,
              maximumDiskBytes > 0,
              maximumSingleSnapshotBytes > 0,
              pollIntervalMilliseconds > 0 else {
            throw ConfigurationError.invalidLimits
        }
    }
}

enum ConfigurationError: Error, Equatable {
    case invalidLimits
}
